### ISSUE TITLE
Subcategories improvements

### ISSUE THREAD

**Issue by sargunv** [shedaniel/Cloth#10]
(1) The arrow is black, which is had to see on a dark background. I recommend setting it to the same color as the text.

![image](https://user-images.githubusercontent.com/1320357/56485969-f3334a00-648a-11e9-836e-1efc0be1c2e4.png)

(2) The subcategory name should be at the same indent as the other fields on its level; only the values inside the subcategory should be indented. This would mean the arrow should render to the left of the text. This would be consistent with other tree style GUIs:

![image](https://user-images.githubusercontent.com/1320357/56486085-545b1d80-648b-11e9-95c5-533ae84d907c.png)

(3) I'd recommend a triangle icon rather than an explicit arrow. Arrow implies a direction, whereas here we just want to indicate collapse status. A triangle shaped button that rotates like the arrow and highlights like a vMC button would be perfect.

**Comment by shedaniel** [comment]
The arrow should be white, not sure what happened. I agree with point 2. I want to change the arrow to + or -

**Comment by sargunv** [comment]
Weird, looks like it's sometimes white, sometimes not:

![image](https://user-images.githubusercontent.com/1320357/56486564-e0217980-648c-11e9-8ef8-d99ffc949dc6.png)

![image](https://user-images.githubusercontent.com/1320357/56486574-ea437800-648c-11e9-9d07-21cfacf04092.png)

**Comment by sargunv** [comment]
+/- would be great too!

**Comment by shedaniel** [comment]
weird huh

**Comment by sargunv** [comment]
I was also able to make the scroll bar go out of its bounds and overlap the bottom button bar:

https://streamable.com/9cyah
