### ISSUE TITLE
Subcategory icons are still black sometimes

### ISSUE THREAD

**Issue by sargunv** [shedaniel/Cloth#12]
![](https://gitlab.com/sargunv-mc-mods/auto-config/wikis/uploads/f7e4d6446c99f26e86a3619db409be44/image.png)

This is on 0.2.0.11.

**Comment by shedaniel** [comment]
this is weird

**Comment by shedaniel** [comment]
try build 12

**Comment by sargunv** [comment]
Still happening under build 12. Reproducible by simply installing the latest auto-config and opening it's example config gui.

**Comment by shedaniel** [comment]
Reproduced when the textfield is in front of the subcategory

**Comment by shedaniel** [comment]
Fixed in Build 13
