### ISSUE TITLE
Tooltip shouldn't render on the left if the left has less space than right

### ISSUE THREAD

**Issue by sargunv** [shedaniel/Cloth#13]
Currently, the tooltip renders to the right of the cursor unless it can't fit, in which case it renders to the left. This logic results in the tooltip sometimes rendering on the left even when more of it would be visible on the right. It should only render on the left iff it doesn't fit on the right and the mouse is to the right of the center of the screen.

https://streamable.com/ov6ko

**Comment by shedaniel** [comment]
Blame mojang for that

**Comment by shedaniel** [comment]
Blame mojang for that

**Comment by sargunv** [comment]
Oh, didn't realize tooltips are a Mojang thing. I may add an auto-wrapping option to auto-config to work around it.
