### ISSUE TITLE
Reset is not detected as change

### ISSUE THREAD

**Issue by Dinolek** [shedaniel/Cloth#17]
Basically when I do any change, save it, then go back to config menu and click the reset button it doesn't detect it as a change, which causes "Save Changes" button to be not clickable.

**Comment by shedaniel** [comment]
Which mod's config are you trying to change? As a dev or an user?

**Comment by Dinolek** [comment]
I noticed it with my mod, but seems to happen with all of them.
Just noticed that it only seems to happen with slider(int).

**Comment by shedaniel** [comment]
Ah I forgot the `setEdited` in https://github.com/shedaniel/Cloth/blob/72268e772067c2e07625478c6956672c782d8106/src/main/java/me/shedaniel/cloth/gui/entries/IntegerSliderEntry.java#L46-L50
Will fix this later

**Comment by shedaniel** [comment]
Fixed in build 17
