### ISSUE TITLE
Fabric need update?

### ISSUE THREAD

**Issue by flier268** [shedaniel/Cloth#18]
![image](https://user-images.githubusercontent.com/19989232/58864233-e8eda800-86e6-11e9-8167-0ec5dfac6459.png)

**Comment by shedaniel** [comment]
Where are you getting cloth from? Join the discord for support: https://discord.gg/rbxu4Fk GitHub is only for bugs.

**Comment by flier268** [comment]
https://minecraft.curseforge.com/projects/cloth-config

**Comment by shedaniel** [comment]
Would you join the discord? Or I mean where did you get cloth from. (The maven)

**Comment by flier268** [comment]
I don't know how to use maven,so I download it from curseforge.
After I clone jroject and build it,I got a "ClothConfig-0.2.4.17-dev.jar"
Import this library,it work now

**Comment by shedaniel** [comment]
Please don't, just add these mavens:
```
repositories {
    maven { url "https://minecraft.curseforge.com/api/maven" }
}

dependencies {
    modCompile "cloth-config:ClothConfig:0.2.4.17"
    
    // The following line is optional but recommended.
    include "cloth-config:ClothConfig:0.2.4.17"
}
```
