### ISSUE TITLE
[Mod conflict] crashes with Charm AND Builders blocks

### ISSUE THREAD

**Issue by K0-RR** [shedaniel/Cloth#28]
Running Builders blocks and Charm without cloth-api doesn't crash. Running Builders blocks and cloth-api without Charm doesn't crash too.
Reported to [Builders blocks](https://github.com/TiphaineLAURENT/Builders-blocks/issues/9) and [Charm](https://github.com/svenhjol/Charm/issues/410) too

crash report - https://hatebin.com/wknndouhkr
latest.log - https://hatebin.com/hdgwwzanja

**Comment by shedaniel** [comment]
Doesn't seem like a cloth issue, may you try reproducing this issue without cloth api with you entering the game and opening the vanilla recipe book?

**Comment by K0-RR** [comment]
I will try later, now I'm making another issue.

**Comment by shedaniel** [comment]
not cloth
