### ISSUE TITLE
Install Cloth-Client-Events v0 2-

### ISSUE THREAD

**Issue by RimuruT3mpest** [shedaniel/Cloth#37]
I'll leave you with this picture
![image](https://user-images.githubusercontent.com/83413000/139148973-49400df3-68f5-4d77-917c-1f2581bb69d2.png)

**Comment by shedaniel** [comment]
Did you install Cloth API, then it would work, use the CurseForge app for modding installation if you don't understand what you are doing.

**Comment by TheRealGramdalf** [comment]
Note to user who stumble across this like I did: It requires Cloth API Specifically - not cloth config, which is on modrinth. At the time of this post (july 2022) Cloth API can only be found on curseforge. Link: https://www.curseforge.com/minecraft/mc-mods/cloth-api
