### ISSUE TITLE
Release on modrinth.com

### ISSUE THREAD

**Issue by CodeF53** [shedaniel/Cloth#38]
Modrinth is an alternative to curseforge which is way better in a few key aspects:
  -  Proper filtering
     - on curseforge you can search for 1.17 mods, or fabric mods, not 1.17 fabric mods
     - it also has client/server mod filters
  -  Fast searches
     -  It takes nanoseconds for the search results to update to what you have typed, as opposed to the 3-5 seconds curseforge does
  - Easier API integration
     - Well documented, easy to use api
     - You can ask for support from actual humans

It's a pain to have to go to curseforge to get your mod when its required by mods found on this site.

**Comment by shedaniel** [comment]
Not until revenue sharing is implemented.

**Comment by xanthian** [comment]
> It's a pain to have to go to curseforge to get your mod when its required by mods found on this site.

I'm interested to know how many mods are only on Modrinth, as I would say far more are on CF.

**Comment by CodeF53** [comment]
Far more are on curseforge because it has been around for a long time.

A large majority of new mods are on modrinth, and I know of 5 mods I use daily that at least were Modrinth exclusive

**Comment by Lefted** [comment]
I'm sorry to bump this again but has the situation on this changed?
I've read that modrinth will remember the payouts:
> While creator payouts cannot yet be claimed, all ad revenue from this date forward will be claimable once payouts are released

You did release Cloth Config API. Thus wouldn't it be convenient to release Cloth API too?
