### ISSUE TITLE
java.lang.RuntimeException: Mixin transformation of net.minecraft.class_309 failed

### ISSUE THREAD

**Issue by GGamer6458** [shedaniel/Cloth#39]
Minecraft crashes when using Architectury v1.27.46.
No crash when using Architectury v1.26.37, including mods listed below.
[crash-2021-12-30_01.47.09-client.txt](https://github.com/shedaniel/cloth-api/files/7791122/crash-2021-12-30_01.47.09-client.txt)

Cloth API v1.5.50
Minecraft version: 1.16.5
Fabric Loader: 0.12.12
Java: OpenJDK 64-Bit Server VM 17
Mods used when crash happened:
![mods folder](https://user-images.githubusercontent.com/72705840/147713302-2bb7d872-d699-4c62-b32b-7945285c5a06.png)

**Comment by Fairweather-Furry** [comment]
I have the same issue with Architectury versions 1.26.43 and above, Minecraft Fabric 1.16.5. I've tested with only Cloth-API, Architectury, and Fabric itself, the crash happens on Most recent updates for the mods.
[latest.log](https://github.com/shedaniel/cloth-api/files/7800230/latest.log)
[crash-2022-01-02_22.03.23-client.txt](https://github.com/shedaniel/cloth-api/files/7800233/crash-2022-01-02_22.03.23-client.txt)
The mod author for Architectury claims this is a Cloth API error, not an Architectury one, but it seems to me more like a conflict between both. https://github.com/architectury/architectury-api/issues/169

**Comment by kawalain** [comment]
Same issue here but without Architectury

[crash-2022-01-18_02.24.59-client.txt](https://github.com/shedaniel/cloth-api/files/7883790/crash-2022-01-18_02.24.59-client.txt)

```
[02:24:59] [Render thread/ERROR]: Critical injection failure: LVT in net/minecraft/class_309::method_1466(JIIII)V has incompatible changes at opcode 321 in callback cloth-client-events-v0.mixins.json:MixinKeyboard->@Inject::onKeyAfter(JIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_437;Z[Z)V from mod cloth-client-events-v0.
 Expected: [Lnet/minecraft/class_437;, Z, [Z]
    Found: [Lnet/minecraft/class_437;, [Z]
Available: [Lnet/minecraft/class_437;, [Z]
```

Used mods:

	- advanced_runtime_resource_pack 0.5.1 via extrasounds
	- autoswitch 3.5.0
	- autoswitch-api 1.0.0 via autoswitch
	- blue_endless_jankson 1.2.1 via jankson
	- bobby 3.1.0
	- caffeineconfig 1.0.0 via sodium-extra
	- cardinal-components-base 4.0.0 via equipmentcompare
	- cardinal-components-entity 4.0.0 via equipmentcompare
	- chesttracker 1.1.9
	- cloth-api 3.1.58
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.1.58 via cloth-api
	- cloth-common-events-v1 3.1.58 via cloth-api
	- cloth-config 6.1.48
	- cloth-datagen-api-v1 3.1.58 via cloth-api
	- cloth-scissors-api-v1 3.1.58 via cloth-api
	- cloth-utils-v1 3.1.58 via cloth-api
	- com_typesafe_config 1.4.1 via confabricate
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- confabricate 2.1.0-SNAPSHOT+4.1.1 via bobby
	- continuity 1.0.3+1.18
	- cosmetica 0.3.2 via visuality
	- cullleaves 2.3.2
	- eatinganimationid 1.2
	- equipmentcompare 1.2.11
	- extrasounds 2.2.0+1.18
	- fabric 0.46.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8 via bobby
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d95c8 via bobby
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
	- fabric-renderer-api-v1 0.4.10+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.13+b0b66fc365 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-conditions-api-v1 1.0.1+13eda06565 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.1.0+0a73a6c265 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fallingleaves 1.8.1+1.18.1
	- fpsdisplay 1.4.2+1.18
	- goosik-config 0.2.0 via visuality
	- iceberg 1.0.38
	- illuminations 1.10.2
	- indium 1.0.2-alpha2+mc1.18.1
	- inventoryhud 3.4.2
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- iris 1.1.5
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kirin 1.10.0-beta.2 via presencefootsteps
	- krypton 0.1.6
	- lambdabettergrass 1.2.1+1.17
	- lambdynlights 2.1.0+1.17
	- lazydfu 0.1.2
	- libgui 5.0.0-beta.2+1.18-rc1 via chesttracker
	- libninepatch 1.1.0 via libgui
	- libzoomer 0.3.0+1.17.1 via okzoomer
	- lithium 0.7.6
	- midnightlib 0.3.1
	- minecraft 1.18.1
	- modmenu 3.0.1
	- namepain 1.4.0
	- notenoughanimations 1.4.0
	- notenoughcrashes 4.1.3+1.18.1
	- okzoomer 5.0.0-beta.3+1.17.1
	- org_aeonbits_owner_owner 1.0.12 via autoswitch
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- org_quiltmc_quilt-json5 1.0.0 via okzoomer
	- org_slf4j_slf4j-api 1.7.12 via iris
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- physicsmod 2.6.4
	- pinglist 1.3.3
	- presencefootsteps 1.4.0
	- pride 1.1.0+1.17 via lambdynlights
	- reeses-sodium-options 1.2.4
	- smoothswapping 0.4.4
	- sodium 0.4.0-alpha6+build.14
	- sodium-extra 0.3.8
	- soundcategories 1.2.0+1.18 via extrasounds
	- soundphysics 0.5.2
	- spruceui 3.3.0+1.17 via lambdabettergrass
	- starlight 1.0.0+fabric.d0a3220
	- visuality 0.4.0
	- visualoverhaul 4.0.0
	- whereisit 1.14.7 via chesttracker
	- wthit 4.4.0

**Comment by shedaniel** [comment]
This has been fixed now! Update Cloth API to fix this
