### ISSUE TITLE
Minecraft 1.18.1 couldn't start at all

### ISSUE THREAD

**Issue by Fleepe0** [shedaniel/Cloth#41]
I don't have any mods, only latest Fabric API 0.46.1 and Cloth API 3.1.58, but it works fine with Cloth API 3.0.55
I use MultiMC

[crash-2022-01-17_22.40.14-client.txt](https://github.com/shedaniel/cloth-api/files/7884309/crash-2022-01-17_22.40.14-client.txt)
[latest.log](https://github.com/shedaniel/cloth-api/files/7884311/latest.log)

**Comment by CapoFantasma97** [comment]
Same here. even with just Cloth API v3.1.58 enabled and nothing else, the game crashes.

**Comment by Ramiels** [comment]
same issue; worked my way down by removing half mods and found that cloth API 1.17.1 was the culprit. tried alone and same results, I get a
```
[Render thread/ERROR]: Critical injection failure: LVT in net/minecraft/class_309::method_1466(JIIII)V has incompatible changes at opcode 321 in callback cloth-client-events-v0.mixins.json:MixinKeyboard->@Inject::onKeyAfter(JIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_437;Z[Z)V from mod cloth-client-events-v0.
```
right before the crash.
