### ISSUE TITLE
OptiFine/OptiFabric compatibility issue (1.18.1)

### ISSUE THREAD

**Issue by TheSourOnion** [shedaniel/Cloth#44]
There is an issue with Optifine and this mod. Every time the two mods are installed together the game crashes. It doesn't leave a crash report as it's just an issue between two mods. If you could, please fix this ASAp, as almost every mod I use needs Cloth API. 

Also, if you could, please bring back your support channel on discord as it's the only way I can get a straight answer on the issue.

**Comment by Disguys** [comment]
Will leave in this topic a crash log with an error launching OptiFabric and Cloth API on MC version 1.18.1 @shedaniel 
[crash-2022-02-13_20.23.40-client.txt](https://github.com/shedaniel/cloth-api/files/8056167/crash-2022-02-13_20.23.40-client.txt)

**Comment by shedaniel** [comment]
We don't support OptiFabric, it is on them to do so.
