### ISSUE TITLE
Latest version of the API makes the game crash instantly (1.18.1)

### ISSUE THREAD

**Issue by RaptaG** [shedaniel/Cloth#47]
The only working version is 3.0.55..
My mods:

> 3dSkinLayers-Fabric-mc1.18-1.4.0.jar
> AdvancementPlaques-1.18-fabric-1.4.3.jar
> architectury-3.6.13.jar
> armorchroma-1.2.0.jar
> armorhotswap-fabric-1.18-1.7.jar
> autoswitch-3.5.0.jar
> betterdroppeditems-1.3.1-21w37a.jar
> BetterF3-1.2.2-Fabric-1.18.jar
> betterfpsdist-fabric-1.18-1.5.jar
> chat-up-2.0.0.jar
> chat_heads-0.6.0-fabric-1.18.1.jar
> cloth-api-3.0.55.jar
> cloth-config-6.2.57-fabric.jar
> Controlling-fabric-1.18.1-9.0+13.jar
> custom-crosshair-mod-v1.3.8-fabric-mc1.18.1.jar
> DynamicSurroundings-Fabric-1.18.1-0.0.4.jar
> easiervillagertrading-1.18-fabric0.43.1-1.5.4.jar
> EasyMagic-v3.2.1-1.18.1-Fabric.jar
> EditSign-1.18.1-2.2.7.jar
> effective-1.1.jar
> emotecraft-for-MC1.17.1+1.18-2.1-SNAPSHOT-build.9-fabric.jar
> EnhancedSearchability-2.0.2.jar
> EntityCulling-Fabric-1.3.3.jar
> Fabric-1.18-SmoothSwapping-0.4.4.jar
> fabric-api-0.46.4+1.18.jar
> fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar
> fallingleaves-1.9.0+1.18.1.jar
> ForgeConfigAPIPort-v3.1.1-1.18.1-Fabric.jar
> fpsdisplay-1.4.2+1.18.jar
> freelook-1.1.1.jar
> i-am-very-smart-2.1.0+mc1.16.1.jar
> Iceberg-1.18.1-fabric-1.0.38.jar
> image2map-0.2.2.jar
> InventoryHUD-fabric-[1.18]+-3.4.2.jar
> item-model-fix-1.0.3+1.18.jar
> malilib-fabric-1.18.1-0.11.5.jar
> MinecraftCapes+Fabric+1.18.1-12.0.2.jar
> minihud-fabric-1.18.1-0.21.3.jar
> minimalmenu-1.18.1-0.1.4.jar
> modifier-tooltip-fix-1.0.1+MC1.16.5.jar
> modmenu-3.0.1.jar
> notenoughanimations-fabric-1.4.0-mc1.18-pre1.jar
> notenoughcrashes-4.1.4+1.18.1-fabric.jar
> okzoomer-5.0.0-beta.3+1.17.1.jar
> optifabric-1.12.10.jar
> OptiFine_1.18.1_HD_U_H4.jar
> paperdoll-fabric-1.0.0-mc1.18-pre1.jar
> PresenceFootsteps-1.4.0.jar
> PuzzlesLib-v3.1.3-1.18.1-Fabric.jar
> replanter-fabric-1.18-1.3.jar
> replaymod-1.18.1-2.6.3.jar
> shulkerboxtooltip-3.0.5+1.18.jar
> signtools-fabric.1.18-1.0.0.jar
> simple-rpc-fabric-1.18.x-2.7.1.jar
> slight-gui-modifications-2.0.3.jar
> smoothboot-fabric-1.18-1.7.0.jar
> SmoothScrollingEverywhere-3.0.4.jar
> torohealth-1.18-fabric-2.jar
> VisualWorkbench-v3.1.0-1.18.1-Fabric.jar
> WaveyCapes-fabric-1.0.4-mc1.18-pre1.jar
> worldedit-mod-7.2.9.jar
> WorldEditCUI-1.18.1+01.jar
> Xaeros_Minimap_22.1.2_Fabric_1.18.jar

**Comment by shedaniel** [comment]
Re-open with the logs
