### ISSUE TITLE
Crash at startup with latest version of REI

### ISSUE THREAD

**Issue by MoonlightSystem** [shedaniel/Cloth#6]
this is a repost from  [here](https://github.com/shedaniel/RoughlyEnoughItems/issues/55)

The game crashed on startup with REI(with ClothAPI) and a couple other mods

[here is the log](https://github.com/shedaniel/RoughlyEnoughItems/files/3060725/latest.log)
Mods list:
![image](https://user-images.githubusercontent.com/8211402/55836584-d46ca500-5ad3-11e9-90ba-f4539a8e290f.png)

**Comment by shedaniel** [comment]
For now download Cloth Events and drop it into the mods folder, I will try to work it out

**Comment by shedaniel** [comment]
Let's go back https://github.com/shedaniel/RoughlyEnoughItems/issues/55
