### ISSUE TITLE
 Need 1.20+ Cloth API  ,Urgent need！！！

### ISSUE THREAD

**Issue by FengGeNet0324** [shedaniel/Cloth#65]
At present, the latest version of the Cloth API on Curseforge is 1.19, but I need the 1.20.1 version of the Cloth API to create the integration package. Because the IngameIME and 'Slight' Gui Modifications modules require this mod as a front-end, please update the 1.20+Cloth API as soon as possible. Thank you very much!!!

**Comment by HhiPyrene** [comment]
Discord: ”Cloth API基本上已被Architectury API取代”；'Slight' GUI Modifications不需要Cloth API前置

**Comment by FengGeNet0324** [comment]
谢谢您的回信，但这并没有解决所有的问题



虽然您已给出'Slight' GUI Modifications模组的前置解决方法，但是IngameIME[游戏内输入法]模组的问题并没有解决，

此模组与界面微调一样，同样需要Cloth API作为前置，这个模组很重要，目前处于半弃坑状态，
但它对中国大陆Minecraft玩家的游戏聊天体验有很大的帮助
希望您考虑继续更新Cloth API

                       
原始邮件
                       
                     

发件人："HhiPyrene"< ***@***.*** &gt;;

发件时间：2023/7/17 11:56

收件人："shedaniel/cloth-api"< ***@***.*** &gt;;

抄送人："Ziyoufeng0526"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [shedaniel/cloth-api]  Need 1.20+ Cloth API  ,Urgent need！！！ (Issue #65)




 
Discord: ”Cloth API基本上已被Architectury API取代”；'Slight' GUI Modifications不需要Cloth API前置

**Comment by shedaniel** [comment]
那是一個錯誤的角度去看這個問題。'Slight' Gui Modifications已不再需要Cloth API這個前置，Cloth API的功能已大部分被Architectury所取代，IngameIME也可以轉移至使用Architectury API。
